const DEFAULT_API="https://business-analysis-v3-api.onrender.com";
function api(){return localStorage.getItem('ba_api')||DEFAULT_API}
function token(){return localStorage.getItem('ba_token')}
async function req(path,opts={}){opts.headers={...(opts.headers||{}),Authorization:`Bearer ${token()}`};let r=await fetch(api()+path,opts);if(!r.ok)throw new Error((await r.text())||r.statusText);return r.json()}
async function login(){let a=document.getElementById('api').value.trim()||DEFAULT_API,e=document.getElementById('email').value.trim(),p=document.getElementById('password').value;localStorage.setItem('ba_api',a.replace(/\/$/,''));try{let r=await fetch(api()+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:e,password:p})});if(!r.ok)throw new Error(await r.text());let d=await r.json();localStorage.setItem('ba_token',d.access_token);localStorage.setItem('ba_user',JSON.stringify(d.user));location.href='dashboard.html'}catch(x){document.getElementById('msg').textContent='Login failed: '+x.message}}
function logout(){localStorage.removeItem('ba_token');location.href='login.html'}
async function loadDashboard(){let u=JSON.parse(localStorage.getItem('ba_user')||'{}');document.getElementById('role').textContent=u.role||'';let d=u.role==='OWNER'?await req('/api/owner/overview'):await req('/api/client/dashboard');let t=d.totals||d;document.getElementById('root').innerHTML=`<div class="grid">${[['Revenue',t.revenue||0,'R '],['Cost',t.cost||0,'R '],['Profit',t.profit||0,'R '],['Margin',t.margin||0,'%'],['Rows',t.rows||0,''],['Datasets',t.datasets||t.clients||0,'']].map(x=>`<div class="card"><div class="muted">${x[0]}</div><h2>${x[2]}${Number(x[1]).toLocaleString(undefined,{maximumFractionDigits:2})}</h2></div>`).join('')}</div><div class="card" style="margin-top:18px"><h2>V3 Professional Dashboard</h2><p class="muted">Use the Windows desktop app for full interactive filtering, charts, data-quality analysis and exports. The web workspace provides secure role-based account access and owner monitoring.</p></div>`}
async function loadClients(){let u=JSON.parse(localStorage.getItem('ba_user')||'{}');if(u.role!=='OWNER'){return loadDashboard()}let rows=await req('/api/owner/clients');document.getElementById('title').textContent='Owner Control Center';document.getElementById('root').innerHTML=`<div class="grid"><div class="card"><div class="muted">Clients</div><h2>${rows.length}</h2></div><div class="card"><div class="muted">Active</div><h2>${rows.filter(x=>x.status==='active').length}</h2></div><div class="card"><div class="muted">Datasets</div><h2>${rows.reduce((a,x)=>a+x.datasets,0)}</h2></div></div><div class="card" style="margin-top:18px"><h2>Client Portfolio</h2><table class="table"><thead><tr><th>Client</th><th>Status</th><th>Users</th><th>Datasets</th><th>Revenue</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.name}</td><td>${x.status}</td><td>${x.users}</td><td>${x.datasets}</td><td>R ${Number(x.revenue).toLocaleString()}</td></tr>`).join('')}</tbody></table></div>`}
if(location.pathname.endsWith('dashboard.html')){if(!token())location.href='login.html';else loadDashboard().catch(e=>document.getElementById('root').innerHTML='<div class="card">Session error. Please sign in again.</div>')}
